START TRANSACTION;
DROP TABLE IF EXISTS `#__jshopping_search`;
CREATE TABLE IF NOT EXISTS `#__jshopping_search` (
  `keyword` text NOT NULL,
  `links` text NOT NULL,
  `id` int(11) NOT NULL,
  `title` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `#__jshopping_search` (`keyword`, `links`, `id`, `title`) VALUES
('TAXES', 'index.php?option=com_jshopping&controller=taxes', 1, 'Options / Taxes'),
('EXTENDED TAX RULE FOR', 'index.php?option=com_jshopping&controller=exttaxes&back_tax_id=1', 2, 'Options / Taxes / Extended rule tax'),
('OPTIONS', 'index.php?option=com_jshopping&controller=other', 3, 'Options'),
('MANUFACTURERS', 'index.php?option=com_jshopping&controller=manufacturers', 4, 'Options / Manufactorers'),
('COUPONS', 'index.php?option=com_jshopping&controller=coupons', 5, 'Options / Coupons'),
('CURRENCIES,CURRENCY', 'index.php?option=com_jshopping&controller=currencies', 6, 'Options / Currencies'),
('PAYMENTS', 'index.php?option=com_jshopping&controller=payments', 7, 'Options / Payments'),
('SHIPPING METHODS', 'index.php?option=com_jshopping&controller=shippings', 8, 'Options / Shipping methods'),
('SHIPPING PRICES', 'index.php?option=com_jshopping&controller=shippingsprices', 9, 'Options / Shipping prices'),
('DELIVERY TIME', 'index.php?option=com_jshopping&controller=deliverytimes', 10, 'Options / Delivery time'),
('ORDER STATUS', 'index.php?option=com_jshopping&controller=orderstatus', 11, 'Options / Order status'),
('COUNTRY LIST,COUNTRIES,COUNTRY', 'index.php?option=com_jshopping&controller=countries', 12, 'Options / Country list'),
('ATTRIBUTES', 'index.php?option=com_jshopping&controller=attributes', 13, 'Options / Attributes'),
('FREE ATTRIBUTES', 'index.php?option=com_jshopping&controller=freeattributes', 14, 'Options / Free attributes'),
('UNITS OF MEASURE,UNITS', 'index.php?option=com_jshopping&controller=units', 15, 'Options / Units of measure'),
('USER GROUPS,USERGROUPS', 'index.php?option=com_jshopping&controller=usergroups', 16, 'Options / User groups'),
('VENDORS', 'index.php?option=com_jshopping&controller=vendors', 17, 'Options / Vendors'),
('PRODUCT COMMENTS,REVIEW', 'index.php?option=com_jshopping&controller=reviews', 18, 'Options / Product comments'),
('PRODUCT LABELS,LABELS', 'index.php?option=com_jshopping&controller=productlabels', 19, 'Options / Product labels'),
('PRODUCT CHARACTERISTICS,CHARACTERISTICS', 'index.php?option=com_jshopping&controller=productfields', 20, 'Options / Product Characteristics'),
('IMPORT & EXPORT,IMPORT,EXPORT,IMPORT EXPORT,IMPORTEXPORT', 'index.php?option=com_jshopping&controller=productfields', 21, 'Options / Import & Export'),
('ADDONS', 'index.php?option=com_jshopping&controller=addons', 22, 'Options / Addons'),
('FORMULA CALCULATOR,FORMULA,CALCULATOR,FORMULACALCULATOR', 'index.php?option=com_jshopping&controller=formula_calculation', 23, 'Options / Formula calculator'),
('OFFER', 'index.php?option=com_jshopping&controller=offer_and_order', 24, 'Options / Offer'),
('UPLOAD', 'index.php?option=com_jshopping&controller=upload', 25, 'Options / Upload'),
('SHOP FUNCTIONS,FUNCTIONS', 'index.php?option=com_jshopping&controller=config', 26, 'Configuration / Shop functions'),
('GENERAL', 'index.php?option=com_jshopping&controller=config&task=general', 27, 'Configuration / General'),
('PRODUCT', 'index.php?option=com_jshopping&controller=config&task=catprod', 28, 'Configuration / Product'),
('CHECKOUT', 'index.php?option=com_jshopping&controller=config&task=checkout', 29, 'Configuration / Checkout'),
('FIELDS REGISTRATION', 'index.php?option=com_jshopping&controller=config&task=fieldregister', 30, 'Configuration / Fields Registration'),
('CURRENCY', 'index.php?option=com_jshopping&controller=config&task=currency', 31, 'Configuration / Currency'),
('MEDIA', 'index.php?option=com_jshopping&controller=config&task=image', 32, 'Configuration / Media'),
('CONTENT', 'index.php?option=com_jshopping&controller=config&task=content', 33, 'Configuration / Content'),
('SHOP INFO', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 34, 'Configuration / Shop info'),
('OTHER CONFIG', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 35, 'Configuration / Other config'),
('ORDERS', 'index.php?option=com_jshopping&controller=config&task=orders', 36, 'Configuration / Orders'),
('PDF HUB', 'index.php?option=com_jshopping&controller=config&task=pdf', 37, 'Configuration / PDF hub'),
('WISHLIST', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 38, 'Configuration / Shop functions / Enable wishlist'),
('PURCHASE WITHOUT REGISTERING', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 39, 'Configuration / Shop functions / Purchase without registering'),
('USE AS CATALOG', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 40, 'Configuration / Shop functions / Use as catalog'),
('SHIPPINGS', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 41, 'Configuration / Shop functions / Shippings'),
('PAYMENTS', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 42, 'Configuration / Shop functions / Payments'),
('TAX', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 43, 'Configuration / Shop functions / Tax'),
('STOCK', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 44, 'Configuration / Shop functions / Stock'),
('ATTRIBUTES', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 45, 'Configuration / Shop functions / Attributes'),
('FREE ATTRIBUTES', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 46, 'Configuration / Shop functions / Free attributes'),
('DELIVERY TIME', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 47, 'Configuration / Shop functions / Delivery time'),
('VIDEOS', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 48, 'Configuration / Shop functions / Videos'),
('VENDORS', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 49, 'Configuration / Shop functions / Vendors'),
('RELATED PRODUCTS', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 50, 'Configuration / Shop functions / Related products'),
('FILES', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 51, 'Configuration / Shop functions / Files'),
('LABEL', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 52, 'Configuration / Shop functions / Label'),
('PURCHASE PRICE', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 53, 'Configuration / Shop functions / Purchase price'),
('BASIC PRICE', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 54, 'Configuration / Shop functions / Basic price'),
('CHARACTERISTICS', 'index.php?option=com_jshopping&controller=config&task=adminfunction', 55, 'Configuration / Shop functions / Characteristics'),
('SHOP ADMINISTRATOR E-MAIL,SHOP ADMINISTRATOR EMAIL ', 'index.php?option=com_jshopping&controller=config&task=general', 56, 'Configuration / General / Shop administrator E-Mail'),
('DEFAULT LANGUAGE FOR COPYING', 'index.php?option=com_jshopping&controller=config&task=general', 57, 'Configuration / General / Default language for copying'),
('TEMPLATE', 'index.php?option=com_jshopping&controller=config&task=general', 58, 'Configuration / General / Template'),
('DISPLAYING PRICES IN THE ADMIN AREA', 'index.php?option=com_jshopping&controller=config&task=general', 59, 'Configuration / General / Displaying prices in the admin area'),
('DISPLAYING PRICES IN THE FRONT AREA', 'index.php?option=com_jshopping&controller=config&task=general', 60, 'Configuration / General / Displaying prices in the front area'),
('DATE FORMAT', 'index.php?option=com_jshopping&controller=config&task=general', 61, 'Configuration / General / Date format'),
('PRODUCT PRICE PRECISION', 'index.php?option=com_jshopping&controller=config&task=general', 62, 'Configuration / General / Product price precision'),
('NOT REDIRECT IN CART AFTER BUY', 'index.php?option=com_jshopping&controller=config&task=catprod', 63, 'Configuration / Product / Not redirect in cart after buy'),
('HIDE PRODUCTS WHICH ARE NOT AVALIBLE ON THE STOCK', 'index.php?option=com_jshopping&controller=config&task=catprod', 64, 'Configuration / Product / Hide products which are not avalible in stock'),
('HIDE BUY BUTTON WHEN PRODUCT ISN\'T AVALIBLE IN STOCK', 'index.php?option=com_jshopping&controller=config&task=catprod', 65, 'Configuration / Product / Hide buy button when product isn\\\'t available in stock '),
('HIDE TEXT PRODUCT IS NOT AVALIBLE', 'index.php?option=com_jshopping&controller=config&task=catprod', 66, 'Configuration / Product / Hide Text \'product is not available\' '),
('DISPLAY WEIGHT IN', 'index.php?option=com_jshopping&controller=config&task=catprod', 67, 'Configuration / Product / Display weight in '),
('AMOUNT OF PRODUCTS ON PAGE', 'index.php?option=com_jshopping&controller=config&task=catprod', 68, 'Configuration / Product / Amount of products on page '),
('AMOUNT OF MANUFACTURERS ON PAGE', 'index.php?option=com_jshopping&controller=config&task=catprod', 69, 'Amount of manufacturers on page '),
('AMOUNT OF VENDORS ON PAGE', 'index.php?option=com_jshopping&controller=config&task=catprod', 70, 'Configuration / Product / Amount of vendors on page '),
('CATEGORY SORTING', 'index.php?option=com_jshopping&controller=config&task=catprod', 71, 'Configuration / Product / Category sorting '),
('MANUFACTURER SORTING', 'index.php?option=com_jshopping&controller=config&task=catprod', 72, 'Configuration / Product / Manufacturer sorting'),
('PRODUCT SORTING', 'index.php?option=com_jshopping&controller=config&task=catprod', 73, 'Configuration / Product / Product sorting'),
('SORT DIRECTION PRODUCT', 'index.php?option=com_jshopping&controller=config&task=catprod', 74, 'Configuration / Product / Sort direction Product '),
('SHOW PRODUCT WEIGHT', 'index.php?option=com_jshopping&controller=config&task=catprod', 75, 'Configuration / Product / Show product weight '),
('SHOW PRODUCT CODE', 'index.php?option=com_jshopping&controller=config&task=catprod', 76, 'Configuration / Product / Show product Code '),
('QUANTITY IN STOCK', 'index.php?option=com_jshopping&controller=config&task=catprod', 77, 'Configuration / Product / Quantity in stock '),
('SHOW PRICE', 'index.php?option=com_jshopping&controller=config&task=catprod', 78, 'Configuration / Product / Show price '),
('SHOW PLUS SHIPPING', 'index.php?option=com_jshopping&controller=config&task=catprod', 79, 'Configuration / Product / Show \'Plus shipping'),
('SHOW THE EXTRA PRICE FOR THE ATTRIBUTES', 'index.php?option=com_jshopping&controller=config&task=catprod', 80, 'Configuration / Product / Show the extra price for the attributes'),
('SORT ATTRIBUTES OF PRODUCT DEPENDENT', 'index.php?option=com_jshopping&controller=config&task=catprod', 81, 'Configuration / Product / Sort attributes of product (Dependent)'),
('SORT ATTRIBUTES OF PRODUCT INDEPENDENT', 'index.php?option=com_jshopping&controller=config&task=catprod', 82, 'Configuration / Product / Sort attributes of product (Independent)'),
('SHOW PRODUCT CODE', 'index.php?option=com_jshopping&controller=config&task=catprod', 83, 'Configuration / Product / Show product Code '),
('QUANTITY IN STOCK', 'index.php?option=com_jshopping&controller=config&task=catprod', 84, 'Configuration / Product / Quantity in stock '),
('SHOW PRICE', 'index.php?option=com_jshopping&controller=config&task=catprod', 85, 'Configuration / Product / Show price'),
('SHOW PLUS SHIPPING', 'index.php?option=com_jshopping&controller=config&task=catprod', 86, 'Configuration / Product / Show \'Plus shipping\' '),
('SHOW PRICE FOR BASIC MEMBERS', 'index.php?option=com_jshopping&controller=config&task=catprod', 87, 'Configuration / Product / Show Price for Basic members '),
('HIDE SHIPPING STEP USE FIRST', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 88, 'Configuration / Checkout / Hide shipping step (use first) '),
('HIDE PAYMENT STEP USE FIRST', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 89, 'Configuration / Checkout / Hide payment step (use first)'),
('SORT OF COUNTRY IN ALPHABETICAL ORDER', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 90, 'Configuration / Checkout / Sort of the country in alphabetical order'),
('DEFAULT COUNTRY', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 91, 'Configuration / Checkout / Sequence of steps '),
('SHOW PRODUCT WEIGHT', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 92, 'Configuration / Checkout / Show product weight '),
('SHOW PRODUCT CODE', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 93, 'Configuration / Checkout / Show product Code '),
('BASIC PRICE', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 94, 'Configuration / Checkout / Basic price '),
('USED DECIMAL QUANTITY', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 95, 'Configuration / Checkout / Used decimal quantity '),
('TERMS OF SERVICE', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 96, 'Configuration / Checkout / Terms of Service '),
('SHOW RETURN POLICY IN EMAIL ORDER URL', 'http://test/administrator/index.php?option=com_jshopping&controller=config&task=checkout', 97, 'Configuration / Checkout / No return (all product) '),
('REGISTER', 'index.php?option=com_jshopping&controller=config&task=fieldregister', 98, 'Configuration / Fields Registration / Register'),
('ADDRESS', 'index.php?option=com_jshopping&controller=config&task=fieldregister', 99, 'Configuration / Fields Registration / Address'),
('CHANGE MY DETAILS', 'index.php?option=com_jshopping&controller=config&task=fieldregister', 100, 'Configuration / Fields Registration / Changemy details'),
('MAIN CURRENCY', 'index.php?option=com_jshopping&controller=config&task=currency', 101, 'Configuration / Currency / Main currency'),
('DECIMALS', 'index.php?option=com_jshopping&controller=config&task=currency', 102, 'Configuration / Currency / Decimals'),
('DECIMAL SYMBOL', 'index.php?option=com_jshopping&controller=config&task=currency', 103, 'Configuration / Currency / Decimal symbol '),
('THOUSANDS SEPARATOR', 'index.php?option=com_jshopping&controller=config&task=currency', 104, 'Configuration / Currency / Thousands separator '),
('FORMAT', 'index.php?option=com_jshopping&controller=config&task=currency', 105, 'Configuration / Currency / Format'),
('CATEGORY THUMBNAIL WIDTH', 'index.php?option=com_jshopping&controller=config&task=image', 106, 'Configuration / Media / Category thumbnail width '),
('CATEGORY THUMBNAIL HEIGHT', 'index.php?option=com_jshopping&controller=config&task=image', 107, 'Configuration / Media / Category thumbnail height'),
('PRODUCT THUMBNAIL WIDTH', 'index.php?option=com_jshopping&controller=config&task=image', 108, 'Configuration / Media / Product thumbnail width '),
('PRODUCT THUMBNAIL HEIGHT', 'index.php?option=com_jshopping&controller=config&task=image', 109, 'Configuration / Media / Product thumbnail height '),
('PRODUCT IMAGE WIDTH', 'index.php?option=com_jshopping&controller=config&task=image', 110, 'Configuration / Media / Product image width '),
('PRODUCT IMAGE HEIGHT', 'index.php?option=com_jshopping&controller=config&task=image', 111, 'Configuration / Media / Product image height '),
('WIDTH ORIGINAL IMAGE', 'index.php?option=com_jshopping&controller=config&task=image', 112, 'Configuration / Media / Width original image '),
('HEIGHT ORIGINAL IMAGE', 'index.php?option=com_jshopping&controller=config&task=image', 113, 'Configuration / Media / Height original image '),
('PRODUCT VIDEO WIDTH', 'index.php?option=com_jshopping&controller=config&task=image', 114, 'Configuration / Media / Product video width '),
('PRODUCT VIDEO HEIGHT', 'index.php?option=com_jshopping&controller=config&task=image', 115, 'Configuration / Media / Product video height'),
('RESIZE TYPE', 'index.php?option=com_jshopping&controller=config&task=image', 116, 'Configuration / Media / Resize type'),
('IMAGE QUALITY', 'index.php?option=com_jshopping&controller=config&task=image', 117, 'Configuration / Media / Image quality'),
('IMAGE FILL COLOR', 'index.php?option=com_jshopping&controller=config&task=image', 118, 'Configuration / Media / Image fill color'),
('PRODUCT FILE UPLOAD COUNT', 'index.php?option=com_jshopping&controller=config&task=image', 119, 'Configuration / Media / Product file upload count'),
('PRODUCT IMAGE UPLOAD COUNT', 'index.php?option=com_jshopping&controller=config&task=image', 120, 'Configuration / Media / Product image upload count'),
('PRODUCT VIDEO UPLOAD COUNT', 'index.php?option=com_jshopping&controller=config&task=image', 121, 'Configuration / Media / Product video upload count'),
('MAX TOTAL OF DOWNLOAD SALE FILE', 'index.php?option=com_jshopping&controller=config&task=image', 122, 'Configuration / Media / Max total of download sale file'),
('MAX TOTAL OF DAY SALE FILE', 'index.php?option=com_jshopping&controller=config&task=image', 123, 'Configuration / Media / Max total of day sale file'),
('PRIVACY POLICY', 'index.php?option=com_jshopping&controller=config&task=content', 124, 'Configuration / Content / Privacy Policy'),
('TERMS OF SERVICE', 'index.php?option=com_jshopping&controller=config&task=content', 125, 'Configuration / Content / Terms of Service '),
('RETURN POLICY', 'index.php?option=com_jshopping&controller=config&task=content', 126, 'Configuration / Content / Return Policy'),
('ORDER SUCCESS PAGE', 'index.php?option=com_jshopping&controller=config&task=content', 127, 'Configuration / Content / Order Success Page '),
('SHIPPING INFORMATION', 'index.php?option=com_jshopping&controller=config&task=content', 128, 'Configuration / Content / Shipping information'),
('SHOP NAME', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 129, 'Configuration / Shop info / Shop name'),
('COMPANY NAME', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 130, 'Configuration / Shop info / Company name'),
('URL', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 131, 'Configuration / Shop info / URL'),
('LOGO', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 132, 'Configuration / Shop info / Logo'),
('ADDRESS', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 133, 'Configuration / Shop info / Address'),
('CITY', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 134, 'Configuration / Shop info / City'),
('POSTAL CODE', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 135, 'Configuration / Shop info / Postal Code'),
('STATE PROVINCE REGION', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 136, 'Configuration / Shop info / State/Province/Region '),
('COUNTRY', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 137, 'Configuration / Shop info / Country'),
('CONTACT INFO FIRST NAME LAST NAME MIDDLE NAME PHONE FAX EMAIL E-MAIL', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 138, 'Configuration / Shop info / Contact info'),
('BANK NAME BANK IDENTIFICATION CODE ACCOUNT NUMBER PAYEE IBAN BIC SWIFT CODE', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 139, 'Configuration / Shop info / Bank'),
('INTERMEDIARY BANK NAME SWIFT CODE IDENTIFICATION NR TAX NR ADDITIONAL INFORMATION', 'index.php?option=com_jshopping&controller=config&task=storeinfo', 140, 'Configuration / Shop info / Intermediary bank'),
('CART DECIMAL QTY PRECISION', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 141, 'Configuration / Other config / Cart decimal qty precision '),
('LOAD LIGHTBOX', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 142, 'Configuration / Other config / Load Lightbox'),
('LOAD JAVASCRIPT', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 143, 'Configuration / Other config / Load javascript'),
('LOAD CSS', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 144, 'Configuration / Other config / Load css'),
('CALCULATE BASIC PRICE FROM PRODUCT PRICE LIST PRODUCT', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 145, 'Configuration / Other config / Calculate basic price from product price (List products)'),
('CALCULATE BASIC PRICE FROM PRODUCT PRICE', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 146, 'Configuration / Other config / Calculate basic price from product price'),
('SAVE INFO TO LOGFILE', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 147, 'Configuration / Other config / Save info to Logfile '),
('SAVE INFO PAYMENT TO LOGFILE', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 148, 'Configuration / Other config / Save info Payment to Logfile '),
('SECURITY KEY', 'index.php?option=com_jshopping&controller=config&task=otherconfig', 149, 'Configuration / Other config / Security key '),
('DFEFAULT ORDER STATUS', 'index.php?option=com_jshopping&controller=config&task=orders', 150, 'Configuration / Orders / Default order status'),
('NEXT ORDER WILL START NUMBERING FROM', 'index.php?option=com_jshopping&controller=config&task=orders', 151, 'Configuration / Orders / Next order will start numbering from'),
('SUFFIX FOR NUMBER', 'index.php?option=com_jshopping&controller=config&task=orders', 152, 'Configuration / Orders / Suffix for number '),
('CUSTOMER MAY CANCEL AN ORDER', 'index.php?option=com_jshopping&controller=config&task=orders', 153, 'Configuration / Orders / Customer may cancel an order '),
('NOTICE OF ORDER TO THE VENDOR', 'index.php?option=com_jshopping&controller=config&task=orders', 154, 'Configuration / Orders / Notice of Order to the vendor '),
('THE ADMINISTRATOR DOES NOT RECEIVE INFORMATION ABOUT ORDERING, IF THE VENDOR GETS', 'index.php?option=com_jshopping&controller=config&task=orders', 155, 'Configuration / Orders / The Administrator does not receive information about ordering, if the vendor gets '),
('MAXIMUM ORDER PRICE', 'index.php?option=com_jshopping&controller=config&task=orders', 156, 'Configuration / Orders / Maximum order price '),
('MINIMUM ORDER PRICE', 'index.php?option=com_jshopping&controller=config&task=orders', 157, 'Configuration / Orders / Minimum order price '),
('DELIVERY OF ORDER DEPENDS ON DELIVERY OF PRODUCT', 'index.php?option=com_jshopping&controller=config&task=orders', 158, 'Configuration / Orders / Delivery of order depends on delivery of product '),
('FREE SHIPPING FOR ORDER (PRICE) OVER', 'index.php?option=com_jshopping&controller=config&task=orders', 159, 'Configuration / Orders / Free shipping for order (price) over '),
('PDF INVOICE TO THE CUSTOMER', 'index.php?option=com_jshopping&controller=config&task=pdf', 160, 'Configuration / PDF hub / PDF invoice to the customer'),
('PDF INVOICE TO THE ADMIN', 'index.php?option=com_jshopping&controller=config&task=pdf', 161, 'Configuration / PDF hub / PDF invoice to the admin '),
('SEND INVOICE MANUALLY', 'index.php?option=com_jshopping&controller=config&task=pdf', 162, 'Configuration / PDF hub / Send invoice manually '),
('INVOICE DATE', 'index.php?option=com_jshopping&controller=config&task=pdf', 163, 'Configuration / PDF hub / Invoice Date '),
('WEIGHT IN INVOICE', 'index.php?option=com_jshopping&controller=config&task=pdf', 164, 'Configuration / PDF hub / Weight in invoice '),
('SHIPPING IN INVOICE', 'index.php?option=com_jshopping&controller=config&task=pdf', 165, 'Configuration / PDF hub / Shipping in invoice '),
('PAYMENT IN INVOICE', 'index.php?option=com_jshopping&controller=config&task=pdf', 166, 'Configuration / PDF hub / Payment in invoice '),
('CUSTOMER NUMBER IN INVOICE', 'index.php?option=com_jshopping&controller=config&task=pdf', 167, 'Configuration / PDF hub / Сustomer number in invoice '),
('SHOW \'RETRN POLICY\' IN PDF', 'index.php?option=com_jshopping&controller=config&task=pdf', 168, 'Configuration / PDF hub / Show \'return policy\' in PDF'),
('HEADER WIDTH HEIGHT FOOTER PREVIEW PDF', 'index.php?option=com_jshopping&controller=config&task=pdf', 169, 'Configuration / PDF hub / PDF Config'),
('CASH ON DELIVERY', 'index.php?option=com_jshopping&controller=payments&task=edit&payment_id=1', 170, 'Options / Payments / Cash on Delivery'),
('ADVANCE PAYMENT', 'index.php?option=com_jshopping&controller=payments&task=edit&payment_id=2', 171, 'Options / Payments / Advance payment'),
('DELIVERY METHOD PRICES', 'index.php?option=com_jshopping&controller=shippingsprices&shipping_id_back=1', 172, 'Options / Shipping methods / Delivery method prices'),
('STANDARD', 'index.php?option=com_jshopping&controller=shippings&task=edit&shipping_id=1', 173, 'Options / Shipping methods / Standard'),
('EXPRESS', 'index.php?option=com_jshopping&controller=shippings&task=edit&shipping_id=2', 174, 'Options / Shipping methods / Express'),
('STANDARD', 'index.php?option=com_jshopping&controller=shippingsprices&task=edit&sh_pr_method_id=1&shipping_id_back=0', 175, 'Options / Shipping prices / Standard'),
('EXPRESS', 'index.php?option=com_jshopping&controller=shippingsprices&task=edit&sh_pr_method_id=2&shipping_id_back=0', 176, 'Options / Shipping prices / Express'),
('PENDING CONFIRMED CANCELLED REFUNDED SHIPPED PAID COMPLETE REVERSAL', 'index.php?option=com_jshopping&controller=orderstatus', 177, 'Option / Order status'),
('HOURS KG LITER PCS M²', 'index.php?option=com_jshopping&controller=units', 178, 'Options / Units of measure'),
('NEW SALE', 'index.php?option=com_jshopping&controller=productlabels', 179, 'Options / Product labels');
ALTER TABLE `#__jshopping_search`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `#__jshopping_search`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=180;
COMMIT;