CREATE TABLE IF NOT EXISTS `#__jshopping_users_addresses` (
	`address_id` SERIAL,
	`user_id` BIGINT NOT NULL,
	`title` tinyint(1) NOT NULL DEFAULT 0,
	`f_name` varchar(255) NOT NULL,
	`l_name` varchar(255) NOT NULL,
	`firma_name` varchar(100) NOT NULL,
	`client_type` tinyint(1) DEFAULT 0,
	`firma_code` varchar(100) NOT NULL,
	`tax_number` varchar(100) NOT NULL,
	`email` varchar(255) NOT NULL,
	`street` varchar(255) NOT NULL,
	`home` varchar(20) NOT NULL,
	`apartment` varchar(20) NOT NULL,
	`zip` varchar(20) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(100) NOT NULL,
	`country` int(11) DEFAULT 0,
	`phone` varchar(20) NOT NULL,
	`mobil_phone` varchar(20) NOT NULL,
	`fax` varchar(20) NOT NULL,
	`ext_field_1` varchar(255) NOT NULL,
	`ext_field_2` varchar(255) NOT NULL,
	`ext_field_3` varchar(255) NOT NULL,
	`m_name` varchar(255) NOT NULL,
	`birthday` date NOT NULL,
	`street_nr` varchar(16) NOT NULL,
	`is_default` BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__jshopping_order_addresses` (
	`id` SERIAL,
	`user_id` int(11) NOT NULL,
	`m_name` varchar(255) NOT NULL,
	`f_name` varchar(255) NOT NULL,
	`l_name` varchar(255) NOT NULL,
	`title` tinyint(1) NOT NULL DEFAULT 0,
	`firma_name` varchar(100) NOT NULL,
	`client_type` tinyint(1) DEFAULT 0,
	`firma_code` varchar(100) NOT NULL,
	`tax_number` varchar(100) NOT NULL,
	`email` varchar(255) NOT NULL,
	`street` varchar(255) NOT NULL,
	`home` varchar(20) NOT NULL,
	`apartment` varchar(20) NOT NULL,
	`zip` varchar(20) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(100) NOT NULL,
	`country` int(11) DEFAULT 0,
	`phone` varchar(20) NOT NULL,
	`mobil_phone` varchar(20) NOT NULL,
	`fax` varchar(20) NOT NULL,
	`ext_field_1` varchar(255) NOT NULL,
	`ext_field_2` varchar(255) NOT NULL,
	`ext_field_3` varchar(255) NOT NULL,
	`birthday` date NOT NULL,
	`street_nr` varchar(16) NOT NULL,
	`d_title` tinyint(1) NOT NULL,
	`d_f_name` varchar(255) NOT NULL,
	`d_l_name` varchar(255) NOT NULL,
	`d_firma_name` varchar(100) NOT NULL,
	`d_email` varchar(255) NOT NULL,
	`d_street` varchar(255) NOT NULL,
	`d_home` varchar(20) NOT NULL,
	`d_apartment` varchar(20) NOT NULL,
	`d_zip` varchar(20) NOT NULL,
	`d_city` varchar(100) NOT NULL,
	`d_state` varchar(100) NOT NULL,
	`d_country` int(11) NOT NULL,
	`d_phone` varchar(20) NOT NULL,
	`d_client_type` tinyint(1) DEFAULT 0,
	`d_firma_code` varchar(100) NOT NULL,
	`d_tax_number` varchar(100) NOT NULL,
	`d_mobil_phone` varchar(20) NOT NULL,
	`d_fax` varchar(20) NOT NULL,
	`d_ext_field_1` varchar(255) NOT NULL,
	`d_ext_field_2` varchar(255) NOT NULL,
	`d_ext_field_3` varchar(255) NOT NULL,
	`d_m_name` varchar(255) NOT NULL,
	`d_birthday` date NOT NULL,
	`d_street_nr` varchar(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__jshopping_updates_info` (
	`id` SERIAL,
	`is_copied_user_addresses_to_new_table` tinyint(1) NOT NULL DEFAULT 0,
	`is_copied_orders_addresses_to_new_table` tinyint(1) NOT NULL DEFAULT 0,
	`is_updated_product_price_preview` tinyint(1) NOT NULL DEFAULT 0,
	`is_updated_product_price_group` tinyint(1) NOT NULL DEFAULT 0,
	`is_moved_free_attr_calc_price` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `#__jshopping_updates_info`(`is_copied_user_addresses_to_new_table`, `is_copied_orders_addresses_to_new_table`, `is_updated_product_price_preview`, `is_updated_product_price_group`, `is_moved_free_attr_calc_price`) VALUES(0, 0, 0, 0, 0);

CALL addFieldIfNotExistsWithUnknownPrefixTable('jshopping_orders', 'order_address_id', 'BIGINT UNSIGNED');