DELETE FROM `#__jshopping_order_status` WHERE `status_id` = 40;
DELETE FROM `#__jshopping_order_status` WHERE `status_id` = 41;
DELETE FROM `#__jshopping_order_status` WHERE `status_id` = 42;
INSERT INTO `#__jshopping_order_status`(
	`status_id`,
	`status_code`,
	`name_en-GB`,
	`name_de-DE`,
	`name_es-ES`,
	`name_it-IT`,
	`name_fr-FR`,
	`name_nl-NL`,
	`name_pl-PL`,
	`name_ru-RU`,
	`name_sv-SE`,
	`name_fr-CA`,
	`email_text`,
	`email`,
	`order_status_image`
) VALUES(
	40,
	'H',
	'On hold',
	'In Wartestellung',
	'On hold',
	'On hold',
	'On hold',
	'On hold',
	'On hold',
	'On hold',
	'On hold',
	'On hold',
	'a:4:{s:10:"text_de-DE";s:290:"<p>Guten Tag {first_name} {last_name},</p> <p>Der Status Ihrer Bestellung {order_number} wurde geändert.<br />Neuer Status: {order_status}</p> <p>Einzelheiten:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_en-GB";s:282:"<p>Hello {first_name} {last_name},</p><p>Status of your order number {order_number} has changed<br />New status is: {order_status}</p> <p>Order details:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_nl-NL";s:279:"<p>Hallo {first_name} {last_name},</p> <p>De status van uw bestelling {order_number} is gewijzigd.<br />Nieuwe status: {order_status}</p> <p>Details:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_ru-RU";s:333:"<p>Здравствуйте {first_name} {last_name},</p> <p>Статус вашего заказа {order_number} был изменен.<br />Новый статус: {order_status}</p> <p>Детали:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";}',
	'',
	''
), (
	41,
	'A',
	'Accepted',
	'Akzeptiert',
	'Accepted',
	'Accepted',
	'Accepted',
	'Accepted',
	'Accepted',
	'Accepted',
	'Accepted',
	'Accepted',
	'a:4:{s:10:"text_de-DE";s:290:"<p>Guten Tag {first_name} {last_name},</p> <p>Der Status Ihrer Bestellung {order_number} wurde geändert.<br />Neuer Status: {order_status}</p> <p>Einzelheiten:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_en-GB";s:282:"<p>Hello {first_name} {last_name},</p><p>Status of your order number {order_number} has changed<br />New status is: {order_status}</p> <p>Order details:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_nl-NL";s:279:"<p>Hallo {first_name} {last_name},</p> <p>De status van uw bestelling {order_number} is gewijzigd.<br />Nieuwe status: {order_status}</p> <p>Details:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_ru-RU";s:333:"<p>Здравствуйте {first_name} {last_name},</p> <p>Статус вашего заказа {order_number} был изменен.<br />Новый статус: {order_status}</p> <p>Детали:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";}',
	'',
	''
), (
	42,
	'E',
	'Rejected',
	'Abgelehnt',
	'Rejected',
	'Rejected',
	'Rejected',
	'Rejected',
	'Rejected',
	'Rejected',
	'Rejected',
	'Rejected',
	'a:4:{s:10:"text_de-DE";s:290:"<p>Guten Tag {first_name} {last_name},</p> <p>Der Status Ihrer Bestellung {order_number} wurde geändert.<br />Neuer Status: {order_status}</p> <p>Einzelheiten:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_en-GB";s:282:"<p>Hello {first_name} {last_name},</p><p>Status of your order number {order_number} has changed<br />New status is: {order_status}</p> <p>Order details:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_nl-NL";s:279:"<p>Hallo {first_name} {last_name},</p> <p>De status van uw bestelling {order_number} is gewijzigd.<br />Nieuwe status: {order_status}</p> <p>Details:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";s:10:"text_ru-RU";s:333:"<p>Здравствуйте {first_name} {last_name},</p> <p>Статус вашего заказа {order_number} был изменен.<br />Новый статус: {order_status}</p> <p>Детали:<br />{order_detail_url}<br />{company}<br />{address}<br />{zip} {city}<br />{country}<br />{comment}<br />{phone}<br />{fax}</p>";}',
	'',
	''
);